### ISSUE TITLE
Run test failed on develop branch

### ISSUE THREAD

**Issue by thodinh** [ConsenSys/UniversalToken#135]
## Expected Behavior

I would expect the `yarn coverage` command to run all unit tests for the project.

## Current Behavior

Failed to compile on run `yarn coverage`

I also found it has already occurred here: https://github.com/ConsenSys/UniversalToken/runs/5073650653?check_suite_focus=true

## Steps to Reproduce (for bugs)

1. Git checkout `develop` branch commit `0d0e8361da86f7e0c5890940510049737506616c`
2. Run `yarn`
3. Run `yarn coverage`
4. See message bellow:

```
> Using Truffle library from local node_modules.

> server:            http://127.0.0.1:8555
> truffle:           v5.4.5
> ganache-core:      v2.13.0
> solidity-coverage: v0.8.0-beta.0

Network Info
============
> id:      *
> port:    8555
> network: coverage


Instrumenting for coverage...
=============================

> certificate/ERC1400HoldableCertificateToken.sol
> ERC1400.sol
> erc1820/ERC1820Client.sol
> erc1820/ERC1820Implementer.sol
> erc1820/ERC1820Registry.sol
> ERC20Extendable.sol
> extensions/allowblock/allow/AllowExtension.sol
> extensions/allowblock/allow/IAllowlistedAdminRole.sol
> extensions/allowblock/allow/IAllowlistedRole.sol
> extensions/allowblock/block/BlockExtension.sol
> extensions/allowblock/block/IBlocklistedAdminRole.sol
> extensions/allowblock/block/IBlocklistedRole.sol
> extensions/ERC20/certificates/CertificateLib.sol
> extensions/ERC20/certificates/CertificateValidatorExtension.sol
> extensions/ERC20/certificates/ICertificateValidator.sol
> extensions/ERC20/ERC20Extension.sol
> extensions/ERC20/holds/HoldExtension.sol
> extensions/ExtensionBase.sol
> extensions/ExtensionStorage.sol
> extensions/IExtension.sol
> extensions/IExtensionMetadata.sol
> extensions/IExtensionStorage.sol
> extensions/pausable/IPausable.sol
> extensions/pausable/PauseExtension.sol
> extensions/TokenExtension.sol
> extensions/tokenExtensions/ERC1400TokensChecker.sol
> extensions/tokenExtensions/ERC1400TokensValidator.sol
> extensions/tokenExtensions/IERC1400TokensChecker.sol
> extensions/tokenExtensions/IERC1400TokensValidator.sol
> extensions/userExtensions/IERC1400TokensRecipient.sol
> extensions/userExtensions/IERC1400TokensSender.sol
> helpers/Errors.sol
> IERC1400.sol
> interface/HoldStatusCode.sol
> interface/IERC1643.sol
> interface/IERC1820Implementer.sol
> interface/IERC20HoldableToken.sol
> interface/IHoldableERC1400TokenExtension.sol
> mocks/AllowlistMock.sol
> mocks/BlocklistMock.sol
> mocks/CertificateSignerMock.sol
> mocks/Clock.sol
> mocks/ERC1400TokensRecipientMock.sol
> mocks/ERC1400TokensSenderMock.sol
> mocks/ERC1400TokensValidatorMock.sol
> mocks/ERC20LogicMock.sol
> mocks/FakeERC1400Mock.sol
> mocks/MinterRoleMock.sol
> mocks/PauserMock.sol
> proxy/context/ProxyContext.sol
> roles/AllowlistAdminRole.sol
> roles/AllowlistedRole.sol
> roles/BlocklistAdminRole.sol
> roles/BlocklistedRole.sol
> roles/CertificateSignerRole.sol
> roles/MinterRole.sol
> roles/PauserRole.sol
> roles/Roles.sol
> roles/RolesBase.sol
> tokens/ERC1400HoldableToken.sol
> tokens/ERC20/logic/ERC20Logic.sol
> tokens/ERC20/logic/IERC20Logic.sol
> tokens/ERC20/proxy/ERC20Proxy.sol
> tokens/ERC20/proxy/IERC20Proxy.sol
> tokens/ERC20/storage/ERC20Storage.sol
> tokens/ERC20HoldableToken.sol
> tokens/ERC721/logic/ERC721Logic.sol
> tokens/ERC721/logic/IERC721Logic.sol
> tokens/ERC721/proxy/ERC721Proxy.sol
> tokens/ERC721/proxy/IERC721Proxy.sol
> tokens/ERC721/storage/ERC721Storage.sol
> tokens/extension/ExtendableBase.sol
> tokens/extension/ExtendableHooks.sol
> tokens/extension/ExtendableRouter.sol
> tokens/extension/ExtensionLib.sol
> tokens/extension/IExtensionStorage.sol
> tokens/IToken.sol
> tokens/ITokenLogic.sol
> tokens/roles/ITokenRoles.sol
> tokens/roles/TokenRoles.sol
> tokens/storage/TokenStorage.sol
> tools/BatchBalanceReader.sol
> tools/BatchReader.sol
> tools/BatchTokenIssuer.sol
> tools/DomainAware.sol
> tools/DVPHoldableLockable.sol
> tools/Pausable.sol
> tools/Swaps.sol

Coverage skipped for:
=====================

> Migrations.sol
> tokens/ERC20Token.sol
> tokens/ERC721Token.sol
> tools/FundIssuer.sol

Compiling your contracts...
===========================
> Compiling ./.coverage_contracts/ERC1400.sol
> Compiling ./.coverage_contracts/ERC20Extendable.sol
> Compiling ./.coverage_contracts/IERC1400.sol
> Compiling ./.coverage_contracts/Migrations.sol
> Compiling ./.coverage_contracts/certificate/ERC1400HoldableCertificateToken.sol
> Compiling ./.coverage_contracts/erc1820/ERC1820Client.sol
> Compiling ./.coverage_contracts/erc1820/ERC1820Implementer.sol
> Compiling ./.coverage_contracts/erc1820/ERC1820Registry.sol
> Compiling ./.coverage_contracts/extensions/ERC20/ERC20Extension.sol
> Compiling ./.coverage_contracts/extensions/ERC20/certificates/CertificateLib.sol
> Compiling ./.coverage_contracts/extensions/ERC20/certificates/CertificateValidatorExtension.sol
> Compiling ./.coverage_contracts/extensions/ERC20/certificates/ICertificateValidator.sol
> Compiling ./.coverage_contracts/extensions/ERC20/holds/HoldExtension.sol
> Compiling ./.coverage_contracts/extensions/ExtensionBase.sol
> Compiling ./.coverage_contracts/extensions/ExtensionStorage.sol
> Compiling ./.coverage_contracts/extensions/IExtension.sol
> Compiling ./.coverage_contracts/extensions/IExtensionMetadata.sol
> Compiling ./.coverage_contracts/extensions/IExtensionStorage.sol
> Compiling ./.coverage_contracts/extensions/TokenExtension.sol
> Compiling ./.coverage_contracts/extensions/allowblock/allow/AllowExtension.sol
> Compiling ./.coverage_contracts/extensions/allowblock/allow/IAllowlistedAdminRole.sol
> Compiling ./.coverage_contracts/extensions/allowblock/allow/IAllowlistedRole.sol
> Compiling ./.coverage_contracts/extensions/allowblock/block/BlockExtension.sol
> Compiling ./.coverage_contracts/extensions/allowblock/block/IBlocklistedAdminRole.sol
> Compiling ./.coverage_contracts/extensions/allowblock/block/IBlocklistedRole.sol
> Compiling ./.coverage_contracts/extensions/pausable/IPausable.sol
> Compiling ./.coverage_contracts/extensions/pausable/PauseExtension.sol
> Compiling ./.coverage_contracts/extensions/tokenExtensions/ERC1400TokensChecker.sol
> Compiling ./.coverage_contracts/extensions/tokenExtensions/ERC1400TokensValidator.sol
> Compiling ./.coverage_contracts/extensions/tokenExtensions/IERC1400TokensChecker.sol
> Compiling ./.coverage_contracts/extensions/tokenExtensions/IERC1400TokensValidator.sol
> Compiling ./.coverage_contracts/extensions/userExtensions/IERC1400TokensRecipient.sol
> Compiling ./.coverage_contracts/extensions/userExtensions/IERC1400TokensSender.sol
> Compiling ./.coverage_contracts/helpers/Errors.sol
> Compiling ./.coverage_contracts/interface/HoldStatusCode.sol
> Compiling ./.coverage_contracts/interface/IERC1643.sol
> Compiling ./.coverage_contracts/interface/IERC1820Implementer.sol
> Compiling ./.coverage_contracts/interface/IERC20HoldableToken.sol
> Compiling ./.coverage_contracts/interface/IHoldableERC1400TokenExtension.sol
> Compiling ./.coverage_contracts/mocks/AllowlistMock.sol
> Compiling ./.coverage_contracts/mocks/BlocklistMock.sol
> Compiling ./.coverage_contracts/mocks/CertificateSignerMock.sol
> Compiling ./.coverage_contracts/mocks/Clock.sol
> Compiling ./.coverage_contracts/mocks/ERC1400TokensRecipientMock.sol
> Compiling ./.coverage_contracts/mocks/ERC1400TokensSenderMock.sol
> Compiling ./.coverage_contracts/mocks/ERC1400TokensValidatorMock.sol
> Compiling ./.coverage_contracts/mocks/ERC20LogicMock.sol
> Compiling ./.coverage_contracts/mocks/FakeERC1400Mock.sol
> Compiling ./.coverage_contracts/mocks/MinterRoleMock.sol
> Compiling ./.coverage_contracts/mocks/PauserMock.sol
> Compiling ./.coverage_contracts/proxy/context/ProxyContext.sol
> Compiling ./.coverage_contracts/roles/AllowlistAdminRole.sol
> Compiling ./.coverage_contracts/roles/AllowlistedRole.sol
> Compiling ./.coverage_contracts/roles/BlocklistAdminRole.sol
> Compiling ./.coverage_contracts/roles/BlocklistedRole.sol
> Compiling ./.coverage_contracts/roles/CertificateSignerRole.sol
> Compiling ./.coverage_contracts/roles/MinterRole.sol
> Compiling ./.coverage_contracts/roles/PauserRole.sol
> Compiling ./.coverage_contracts/roles/Roles.sol
> Compiling ./.coverage_contracts/roles/RolesBase.sol
> Compiling ./.coverage_contracts/tokens/ERC1400HoldableToken.sol
> Compiling ./.coverage_contracts/tokens/ERC20/logic/ERC20Logic.sol
> Compiling ./.coverage_contracts/tokens/ERC20/logic/IERC20Logic.sol
> Compiling ./.coverage_contracts/tokens/ERC20/proxy/ERC20Proxy.sol
> Compiling ./.coverage_contracts/tokens/ERC20/proxy/IERC20Proxy.sol
> Compiling ./.coverage_contracts/tokens/ERC20/storage/ERC20Storage.sol
> Compiling ./.coverage_contracts/tokens/ERC20HoldableToken.sol
> Compiling ./.coverage_contracts/tokens/ERC20Token.sol
> Compiling ./.coverage_contracts/tokens/ERC721/logic/ERC721Logic.sol
> Compiling ./.coverage_contracts/tokens/ERC721/logic/IERC721Logic.sol
> Compiling ./.coverage_contracts/tokens/ERC721/proxy/ERC721Proxy.sol
> Compiling ./.coverage_contracts/tokens/ERC721/proxy/IERC721Proxy.sol
> Compiling ./.coverage_contracts/tokens/ERC721/storage/ERC721Storage.sol
> Compiling ./.coverage_contracts/tokens/ERC721Token.sol
> Compiling ./.coverage_contracts/tokens/IToken.sol
> Compiling ./.coverage_contracts/tokens/ITokenLogic.sol
> Compiling ./.coverage_contracts/tokens/extension/ExtendableBase.sol
> Compiling ./.coverage_contracts/tokens/extension/ExtendableHooks.sol
> Compiling ./.coverage_contracts/tokens/extension/ExtendableRouter.sol
> Compiling ./.coverage_contracts/tokens/extension/ExtensionLib.sol
> Compiling ./.coverage_contracts/tokens/extension/IExtensionStorage.sol
> Compiling ./.coverage_contracts/tokens/roles/ITokenRoles.sol
> Compiling ./.coverage_contracts/tokens/roles/TokenRoles.sol
> Compiling ./.coverage_contracts/tokens/storage/TokenStorage.sol
> Compiling ./.coverage_contracts/tools/BatchBalanceReader.sol
> Compiling ./.coverage_contracts/tools/BatchReader.sol
> Compiling ./.coverage_contracts/tools/BatchTokenIssuer.sol
> Compiling ./.coverage_contracts/tools/DVPHoldableLockable.sol
> Compiling ./.coverage_contracts/tools/DomainAware.sol
> Compiling ./.coverage_contracts/tools/FundIssuer.sol
> Compiling ./.coverage_contracts/tools/Pausable.sol
> Compiling ./.coverage_contracts/tools/Swaps.sol
> Compiling @openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol
> Compiling @openzeppelin/contracts-upgradeable/token/ERC20/ERC20Upgradeable.sol
> Compiling @openzeppelin/contracts-upgradeable/token/ERC20/IERC20Upgradeable.sol
> Compiling @openzeppelin/contracts-upgradeable/token/ERC20/extensions/IERC20MetadataUpgradeable.sol
> Compiling @openzeppelin/contracts-upgradeable/utils/AddressUpgradeable.sol
> Compiling @openzeppelin/contracts-upgradeable/utils/ContextUpgradeable.sol
> Compiling @openzeppelin/contracts/access/AccessControl.sol
> Compiling @openzeppelin/contracts/access/AccessControlEnumerable.sol
> Compiling @openzeppelin/contracts/access/Ownable.sol
> Compiling @openzeppelin/contracts/security/Pausable.sol
> Compiling @openzeppelin/contracts/token/ERC20/ERC20.sol
> Compiling @openzeppelin/contracts/token/ERC20/IERC20.sol
> Compiling @openzeppelin/contracts/token/ERC20/extensions/ERC20Burnable.sol
> Compiling @openzeppelin/contracts/token/ERC20/extensions/ERC20Pausable.sol
> Compiling @openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata.sol
> Compiling @openzeppelin/contracts/token/ERC721/ERC721.sol
> Compiling @openzeppelin/contracts/token/ERC721/IERC721.sol
> Compiling @openzeppelin/contracts/token/ERC721/IERC721Receiver.sol
> Compiling @openzeppelin/contracts/token/ERC721/extensions/ERC721Burnable.sol
> Compiling @openzeppelin/contracts/token/ERC721/extensions/ERC721Enumerable.sol
> Compiling @openzeppelin/contracts/token/ERC721/extensions/ERC721Pausable.sol
> Compiling @openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol
> Compiling @openzeppelin/contracts/token/ERC721/extensions/IERC721Enumerable.sol
> Compiling @openzeppelin/contracts/token/ERC721/extensions/IERC721Metadata.sol
> Compiling @openzeppelin/contracts/utils/Address.sol
> Compiling @openzeppelin/contracts/utils/Context.sol
> Compiling @openzeppelin/contracts/utils/StorageSlot.sol
> Compiling @openzeppelin/contracts/utils/Strings.sol
> Compiling @openzeppelin/contracts/utils/introspection/ERC165.sol
> Compiling @openzeppelin/contracts/utils/introspection/IERC165.sol
> Compiling @openzeppelin/contracts/utils/introspection/IERC1820Registry.sol
> Compiling @openzeppelin/contracts/utils/math/SafeMath.sol
> Compiling @openzeppelin/contracts/utils/structs/EnumerableSet.sol

> Compilation warnings encountered:
> solidity-coverage cleaning up, shutting down ganache server
CompileError: DeclarationError: Undeclared identifier.
  --> project:/.coverage_contracts/extensions/allowblock/allow/IAllowlistedRole.sol:13:34:
   |
13 |     modifier onlyNotAllowlisted {c_4caff5b6(0x2539255495eaa41b); /* function */ 
   |                                  ^^^^^^^^^^

,DeclarationError: Undeclared identifier.
  --> project:/.coverage_contracts/extensions/allowblock/allow/IAllowlistedRole.sol:15:1:
   |
15 | c_4caff5b6(0x9c64e4b9363b57f7); /* line */ 
   | ^^^^^^^^^^

,DeclarationError: Undeclared identifier.
  --> project:/.coverage_contracts/extensions/allowblock/allow/IAllowlistedRole.sol:16:9:
   |
16 |         c_4caff5b6(0x114e33d4b02a9e86); /* requirePre */ 
   |         ^^^^^^^^^^

,DeclarationError: Undeclared identifier.
  --> project:/.coverage_contracts/extensions/allowblock/allow/IAllowlistedRole.sol:17:1:
   |
17 | c_4caff5b6(0xa5e3feb41a7de57e); /* statement */ 
   | ^^^^^^^^^^

,DeclarationError: Undeclared identifier.
  --> project:/.coverage_contracts/extensions/allowblock/allow/IAllowlistedRole.sol:18:67:
   |
18 | require(!this.isAllowlisted(msg.sender), "Already on allow list");c_4caff5b6(0xa75e44aa57cd7b43); /* requirePost */ 
   |                                                                   ^^^^^^^^^^

,DeclarationError: Undeclared identifier.
  --> project:/.coverage_contracts/extensions/allowblock/allow/IAllowlistedRole.sol:20:1:
   |
20 | c_4caff5b6(0x2187e7c426e4fd7b); /* line */ 
   | ^^^^^^^^^^

,DeclarationError: Undeclared identifier.
  --> project:/.coverage_contracts/extensions/allowblock/allow/IAllowlistedRole.sol:24:31:
   |
24 |     modifier onlyAllowlisted {c_4caff5b6(0x82f1846bbd955412); /* function */ 
   |                               ^^^^^^^^^^

,DeclarationError: Undeclared identifier.
  --> project:/.coverage_contracts/extensions/allowblock/allow/IAllowlistedRole.sol:26:1:
   |
26 | c_4caff5b6(0xbf16a09dcacf8304); /* line */ 
   | ^^^^^^^^^^

,DeclarationError: Undeclared identifier.
  --> project:/.coverage_contracts/extensions/allowblock/allow/IAllowlistedRole.sol:27:9:
   |
27 |         c_4caff5b6(0x444900d84b8ab208); /* requirePre */ 
   |         ^^^^^^^^^^

,DeclarationError: Undeclared identifier.
  --> project:/.coverage_contracts/extensions/allowblock/allow/IAllowlistedRole.sol:28:1:
   |
28 | c_4caff5b6(0xe7b7451a17c46d89); /* statement */ 
   | ^^^^^^^^^^

,DeclarationError: Undeclared identifier.
  --> project:/.coverage_contracts/extensions/allowblock/allow/IAllowlistedRole.sol:29:62:
   |
29 | require(this.isAllowlisted(msg.sender), "Not on allow list");c_4caff5b6(0x7cd4822056842710); /* requirePost */ 
   |                                                              ^^^^^^^^^^

,DeclarationError: Undeclared identifier.
  --> project:/.coverage_contracts/extensions/allowblock/allow/IAllowlistedRole.sol:31:1:
   |
31 | c_4caff5b6(0xa1f1fd6a27bb0699); /* line */ 
   | ^^^^^^^^^^

Compilation failed. See above.
    at run (/Users/username/code/ERC1400/node_modules/truffle/build/webpack:/packages/compile-solidity/run.js:62:1)
    at Object.sourcesWithDependencies (/Users/username/code/ERC1400/node_modules/truffle/build/webpack:/packages/compile-solidity/index.js:150:1)
    at all (/Users/username/code/ERC1400/node_modules/truffle/build/webpack:/packages/compile-solidity/index.js:81:1)
    at /Users/username/code/ERC1400/node_modules/truffle/build/webpack:/packages/workflow-compile/legacy/index.js:98:31
    at async Promise.all (index 0)
    at Object.compile (/Users/username/code/ERC1400/node_modules/truffle/build/webpack:/packages/workflow-compile/legacy/index.js:50:1)
    at plugin (/Users/username/code/ERC1400/node_modules/solidity-coverage/plugins/truffle.plugin.js:113:5)
Truffle v5.4.5 (core: 5.4.5)
Node v12.18.4
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ecp4224** [comment]
**_The develop branch is under heavy active development and so this is to be expected for now._**

This specific error you are seeing during compilation of the contracts [should be fixed now](https://github.com/ConsenSys/UniversalToken/commit/9c1638b1123010d448ae98c12522a3e18bd5bfc7). Please let me know if you are still running into trouble running `yarn coverage`

**Comment by ecp4224** [comment]
#129 fixes this, `yarn coverage` should now be working
